### ISSUE TITLE
"Error 'entered unreachable code' when using sqlite_connector"

### ISSUE THREAD

**Issue by devitirub** [mycelial/mycelial#162]
---

**Problem Summary:**
I am experiencing an "entered unreachable code" error when using `sqlite_connector` to synchronize data between SQLite databases in the context of the Frigate NVR application.

**Environment:**
- **Operating System:** Ubuntu 22.04
- **Mycelial version:** 0.12.0

**Steps to Reproduce:**
1. Configure the `config.toml` file specifying the SQLite source and destination settings.
2. Start the mycelial server.
3. Start the client daemon that runs the synchronization process.
4. The error occurs immediately after starting the synchronization.

**Note:** I am using the Frigate NVR application which continuously writes to the `frigate.db` database.

---

**Current Behavior:**
The system generates an "entered unreachable code" error and synchronization is interrupted.

**Error Logs:**

**cat daemon.log**
```
2024-05-05T12:52:05.406121Z  INFO myceliald::daemon_storage: connected to "/home/itirub/itirub_stream/config/daemon.db"
2024-05-05T12:52:05.407491Z  INFO myceliald::storage: connected to "/home/itirub/itirub_stream/config/daemon.db"
2024-05-05T12:52:05.408194Z  INFO myceliald::config_watcher: watching "/home/itirub/itirub_stream/config/config.toml"
2024-05-05T12:52:05.419316Z  INFO myceliald::http_client: setting connection info
thread 'tokio-runtime-worker' panicked at pipe/section/section_impls/sqlite_connector/src/source.rs:189:26:
internal error: entered unreachable code
stack backtrace:
   0:     0x5619108f1f96 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5619108f1f96 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5619108f1f96 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5619108f1f96 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5619109217f0 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
   5:     0x5619109217f0 - core::fmt::write::he40921d4802ce2ac
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x5619108ee8cf - std::io::Write::write_fmt::h5de5a4e7037c9b20
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
   7:     0x5619108f1d74 - std::sys_common::backtrace::_print::hd8e2e3f655086663
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5619108f1d74 - std::sys_common::backtrace::print::h11c067a88e3bdb22
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5619108f35d7 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
  10:     0x5619108f3339 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
  11:     0x5619108f3a68 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:781:13
  12:     0x5619108f3909 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:651:13
  13:     0x5619108f2496 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5619108f3694 - rust_begin_unwind
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
  15:     0x56190f576255 - core::panicking::panic_fmt::ha6effc2775a0749c
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
  16:     0x56190f576313 - core::panicking::panic::h44790a89027c670f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:144:5
  17:     0x56190f85329e - sqlite_connector::source::Sqlite::build_sqlite_payload::h0e4988fdf8b94ed6
  18:     0x56190f77b25d - sqlite_connector::source::Sqlite::send_chunk::{{closure}}::h949f3eb05bc13758
  19:     0x56190f7742da - <sqlite_connector::source::Sqlite as section::section::Section<Input,Output,SectionChan>>::start::{{closure}}::h819410e0bf83559b
  20:     0x56190f6cb1f1 - tokio::runtime::task::core::Core<T,S>::poll::hc024756c2a89485c
  21:     0x56190f8401ea - tokio::runtime::task::raw::poll::h2d55b33d3bfdf38d
  22:     0x56191083a14a - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h44ee8ad3f735a668
  23:     0x561910839430 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hb172483b5753ddc1
  24:     0x56191083dd18 - tokio::runtime::context::runtime::enter_runtime::h66e184ad58e55a66
  25:     0x561910838988 - tokio::runtime::scheduler::multi_thread::worker::run::h943b845f9923aa45
  26:     0x561910824643 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h7af49ab418953078
  27:     0x56191082a277 - tokio::runtime::task::core::Core<T,S>::poll::hafff39d6eafe07b6
  28:     0x56191081c98a - tokio::runtime::task::harness::Harness<T,S>::poll::hbc3dc2bd1f53d60f
  29:     0x561910822950 - tokio::runtime::blocking::pool::Inner::run::hf01fd28741231545
  30:     0x56191082b1d7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c06d734b25feae4
  31:     0x56191083c769 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haf53388c616a734f
  32:     0x5619108f8f95 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b630278c760b971
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  33:     0x5619108f8f95 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70462b441b6c0e1f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  34:     0x5619108f8f95 - std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/unix/thread.rs:108:17
  35:     0x7face497aac3 - <unknown>
  36:     0x7face4a0ca40 - <unknown>
  37:                0x0 - <unknown>
2024-05-05T12:52:05.457042Z ERROR runtime::scheduler: pipe with id: 2 stopped: JoinError::Panic(Id(17), ...)
thread 'tokio-runtime-worker' panicked at pipe/section/section_impls/sqlite_connector/src/source.rs:189:26:
internal error: entered unreachable code
stack backtrace:
   0:     0x5619108f1f96 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5619108f1f96 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5619108f1f96 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5619108f1f96 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5619109217f0 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
   5:     0x5619109217f0 - core::fmt::write::he40921d4802ce2ac
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x5619108ee8cf - std::io::Write::write_fmt::h5de5a4e7037c9b20
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
   7:     0x5619108f1d74 - std::sys_common::backtrace::_print::hd8e2e3f655086663
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5619108f1d74 - std::sys_common::backtrace::print::h11c067a88e3bdb22
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5619108f35d7 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
  10:     0x5619108f3339 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
  11:     0x5619108f3a68 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:781:13
  12:     0x5619108f3909 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:651:13
  13:     0x5619108f2496 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5619108f3694 - rust_begin_unwind
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
  15:     0x56190f576255 - core::panicking::panic_fmt::ha6effc2775a0749c
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
  16:     0x56190f576313 - core::panicking::panic::h44790a89027c670f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:144:5
  17:     0x56190f85329e - sqlite_connector::source::Sqlite::build_sqlite_payload::h0e4988fdf8b94ed6
  18:     0x56190f77b25d - sqlite_connector::source::Sqlite::send_chunk::{{closure}}::h949f3eb05bc13758
  19:     0x56190f7742da - <sqlite_connector::source::Sqlite as section::section::Section<Input,Output,SectionChan>>::start::{{closure}}::h819410e0bf83559b
  20:     0x56190f6cb1f1 - tokio::runtime::task::core::Core<T,S>::poll::hc024756c2a89485c
  21:     0x56190f8401ea - tokio::runtime::task::raw::poll::h2d55b33d3bfdf38d
  22:     0x56191083a14a - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h44ee8ad3f735a668
  23:     0x561910839430 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hb172483b5753ddc1
  24:     0x56191083dd18 - tokio::runtime::context::runtime::enter_runtime::h66e184ad58e55a66
  25:     0x561910838988 - tokio::runtime::scheduler::multi_thread::worker::run::h943b845f9923aa45
  26:     0x561910824643 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h7af49ab418953078
  27:     0x56191082a277 - tokio::runtime::task::core::Core<T,S>::poll::hafff39d6eafe07b6
  28:     0x56191081c98a - tokio::runtime::task::harness::Harness<T,S>::poll::hbc3dc2bd1f53d60f
  29:     0x561910822950 - tokio::runtime::blocking::pool::Inner::run::hf01fd28741231545
  30:     0x56191082b1d7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c06d734b25feae4
  31:     0x56191083c769 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haf53388c616a734f
  32:     0x5619108f8f95 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b630278c760b971
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  33:     0x5619108f8f95 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70462b441b6c0e1f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  34:     0x5619108f8f95 - std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/unix/thread.rs:108:17
  35:     0x7face497aac3 - <unknown>
  36:     0x7face4a0ca40 - <unknown>
  37:                0x0 - <unknown>
2024-05-05T12:52:08.467878Z ERROR runtime::scheduler: pipe with id: 2 stopped: JoinError::Panic(Id(28), ...)
thread 'tokio-runtime-worker' panicked at pipe/section/section_impls/sqlite_connector/src/source.rs:189:26:
internal error: entered unreachable code
stack backtrace:
   0:     0x5619108f1f96 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5619108f1f96 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5619108f1f96 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5619108f1f96 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5619109217f0 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
   5:     0x5619109217f0 - core::fmt::write::he40921d4802ce2ac
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x5619108ee8cf - std::io::Write::write_fmt::h5de5a4e7037c9b20
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
   7:     0x5619108f1d74 - std::sys_common::backtrace::_print::hd8e2e3f655086663
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5619108f1d74 - std::sys_common::backtrace::print::h11c067a88e3bdb22
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5619108f35d7 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
  10:     0x5619108f3339 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
  11:     0x5619108f3a68 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:781:13
  12:     0x5619108f3909 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:651:13
  13:     0x5619108f2496 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5619108f3694 - rust_begin_unwind
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
  15:     0x56190f576255 - core::panicking::panic_fmt::ha6effc2775a0749c
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
  16:     0x56190f576313 - core::panicking::panic::h44790a89027c670f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:144:5
  17:     0x56190f85329e - sqlite_connector::source::Sqlite::build_sqlite_payload::h0e4988fdf8b94ed6
  18:     0x56190f77b25d - sqlite_connector::source::Sqlite::send_chunk::{{closure}}::h949f3eb05bc13758
  19:     0x56190f7742da - <sqlite_connector::source::Sqlite as section::section::Section<Input,Output,SectionChan>>::start::{{closure}}::h819410e0bf83559b
  20:     0x56190f6cb1f1 - tokio::runtime::task::core::Core<T,S>::poll::hc024756c2a89485c
  21:     0x56190f8401ea - tokio::runtime::task::raw::poll::h2d55b33d3bfdf38d
  22:     0x56191083a14a - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h44ee8ad3f735a668
  23:     0x561910839430 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hb172483b5753ddc1
  24:     0x56191083dd18 - tokio::runtime::context::runtime::enter_runtime::h66e184ad58e55a66
  25:     0x561910838988 - tokio::runtime::scheduler::multi_thread::worker::run::h943b845f9923aa45
  26:     0x561910824643 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h7af49ab418953078
  27:     0x56191082a277 - tokio::runtime::task::core::Core<T,S>::poll::hafff39d6eafe07b6
  28:     0x56191081c98a - tokio::runtime::task::harness::Harness<T,S>::poll::hbc3dc2bd1f53d60f
  29:     0x561910822950 - tokio::runtime::blocking::pool::Inner::run::hf01fd28741231545
  30:     0x56191082b1d7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c06d734b25feae4
  31:     0x56191083c769 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haf53388c616a734f
  32:     0x5619108f8f95 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b630278c760b971
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  33:     0x5619108f8f95 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70462b441b6c0e1f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  34:     0x5619108f8f95 - std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/unix/thread.rs:108:17
  35:     0x7face497aac3 - <unknown>
  36:     0x7face4a0ca40 - <unknown>
  37:                0x0 - <unknown>
2024-05-05T12:52:11.482274Z ERROR runtime::scheduler: pipe with id: 2 stopped: JoinError::Panic(Id(36), ...)
thread 'tokio-runtime-worker' panicked at pipe/section/section_impls/sqlite_connector/src/source.rs:189:26:
internal error: entered unreachable code
stack backtrace:
   0:     0x5619108f1f96 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5619108f1f96 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5619108f1f96 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5619108f1f96 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5619109217f0 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
   5:     0x5619109217f0 - core::fmt::write::he40921d4802ce2ac
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x5619108ee8cf - std::io::Write::write_fmt::h5de5a4e7037c9b20
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
   7:     0x5619108f1d74 - std::sys_common::backtrace::_print::hd8e2e3f655086663
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5619108f1d74 - std::sys_common::backtrace::print::h11c067a88e3bdb22
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5619108f35d7 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
  10:     0x5619108f3339 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
  11:     0x5619108f3a68 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:781:13
  12:     0x5619108f3909 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:651:13
  13:     0x5619108f2496 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5619108f3694 - rust_begin_unwind
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
  15:     0x56190f576255 - core::panicking::panic_fmt::ha6effc2775a0749c
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
  16:     0x56190f576313 - core::panicking::panic::h44790a89027c670f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:144:5
  17:     0x56190f85329e - sqlite_connector::source::Sqlite::build_sqlite_payload::h0e4988fdf8b94ed6
  18:     0x56190f77b25d - sqlite_connector::source::Sqlite::send_chunk::{{closure}}::h949f3eb05bc13758
  19:     0x56190f7742da - <sqlite_connector::source::Sqlite as section::section::Section<Input,Output,SectionChan>>::start::{{closure}}::h819410e0bf83559b
  20:     0x56190f6cb1f1 - tokio::runtime::task::core::Core<T,S>::poll::hc024756c2a89485c
  21:     0x56190f8401ea - tokio::runtime::task::raw::poll::h2d55b33d3bfdf38d
  22:     0x56191083a14a - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h44ee8ad3f735a668
  23:     0x561910839430 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hb172483b5753ddc1
  24:     0x56191083dd18 - tokio::runtime::context::runtime::enter_runtime::h66e184ad58e55a66
  25:     0x561910838988 - tokio::runtime::scheduler::multi_thread::worker::run::h943b845f9923aa45
  26:     0x561910824643 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h7af49ab418953078
  27:     0x56191082a277 - tokio::runtime::task::core::Core<T,S>::poll::hafff39d6eafe07b6
  28:     0x56191081c98a - tokio::runtime::task::harness::Harness<T,S>::poll::hbc3dc2bd1f53d60f
  29:     0x561910822950 - tokio::runtime::blocking::pool::Inner::run::hf01fd28741231545
  30:     0x56191082b1d7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c06d734b25feae4
  31:     0x56191083c769 - core::ops::function::FnOnce::call_once{{vtable.shim}}::haf53388c616a734f
  32:     0x5619108f8f95 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b630278c760b971
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  33:     0x5619108f8f95 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70462b441b6c0e1f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  34:     0x5619108f8f95 - std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/unix/thread.rs:108:17
  35:     0x7face497aac3 - <unknown>
  36:     0x7face4a0ca40 - <unknown>
  37:                0x0 - <unknown>
2024-05-05T12:52:14.494573Z ERROR runtime::scheduler: pipe with id: 2 stopped: JoinError::Panic(Id(41), ...)
```

**Comment by tbaums** [comment]
Thanks so much for the issue, @devitirub! 

We're gonna take a look tomorrow (9 May), and will get back to you with a fix once we figure out how you hit this.

**Comment by devitirub** [comment]
Thanks for the answer. @tbaums!

**Comment by tbaums** [comment]
Should be fixed @devitirub !

**Comment by tbaums** [comment]
hey @devitirub - just wanted to let you know that we cut a new release this morning with this fix.

If you pull 0.8.2, you'll get this fix AND an updated typecast transformer section that allows you to cast all columns with the `*` operator. Let me know if you have any questions or comments!

**Comment by devitirub** [comment]
I would like to thank you for the response.
I carried out a test with the version made available yesterday and it is working correctly.
I will update to this new version soon.

However, I have a question:
Should I use the libmycelite plugin on the source sqlite database?

**Comment by tbaums** [comment]
Hey @devitirub - Glad it's working correctly! 

Going forward, it's best to use the `sqlite_connector` section rather than mycelite. You can see the params for the sqlite_connector in the example Config.toml here: https://github.com/mycelial/mycelial/blob/main/myceliald/config.example.toml

Let me know if you have any questions!
